name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Debug Information
        run: |
          echo "SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}"
          echo "SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}"
          curl -I ${{ secrets.SONAR_HOST_URL }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
